[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmd = "cd server && npm ci"

[phases.build]
cmd = "cd server && npm run build"

[start]
cmd = "cd server && npm start"
